apiVersion: v1
kind: Service
metadata:
  name: covid-19
  {{- if .Values.service.internal }}
  annotations:
    cloud.google.com/load-balancer-type: Internal
  {{- end }}
  labels:
    app: covid-19
    version: {{ .Values.docker.tag }}
spec:
  selector:
    app: covid-19
  type: {{ .Values.service.type }}
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: 8080